### ISSUE TITLE
Pre - trained weights Required

### ISSUE THREAD

**Issue by kneelace** [cbsudux/Mumbai-slum-segmentation#1]
mask_rcnn_slum_600_00128.h5

this file is missing and google drive link seems to be removed.

plis help!!!

**Comment by cbsudux** [comment]
@abhyantrika

**Comment by abhyantrika** [comment]
https://drive.google.com/file/d/1IIMZLrdCZXY_dA540Ve9lSJplYHLnTY4/view?usp=sharing

**Comment by kneelace** [comment]
thanks a lot sir
--
Nilesh Bhatia
D17C CMPN
VESIT
