### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by msq7071** [cbsudux/Mumbai-slum-segmentation#2]
i run your change_detection code successfully,but i must use the two images you given.When i use my images,dos said:operands could not be broadcast together with remapped shapes.Then i change to the same shape of your two images,dos said: 
 File "change_detection.py", line 117, in get_area
    area = [prop.area for prop in area][0]
IndexError: list index out of range.what's wrong?
Or,could you give a way to download the images like yours?

**Comment by abhyantrika** [comment]
We used 720 X 1024 images. The code resizes this to 1024 X 1024, while maintaining aspect ratio and using padding
